"""Added Name column to COMP_Model

Revision ID: 7360186eb77b
Revises: 
Create Date: 2025-01-14 18:01:47.291517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7360186eb77b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comp__model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comp__model', schema=None) as batch_op:
        batch_op.drop_column('Name')

    # ### end Alembic commands ###
